### PR TITLE
Reducing dependencies, building with xtensor-python

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
To use Scikit-build, you need to map the PYTHON_x variables to Python_x in your CMakeLists. I know I've either done this or seen this done somewhere, but have forgotten where. Hopefully we will fix it soon, it's on the [roadmap](https://github.com/scikit-build/scikit-build/wiki).

**Comment by henryiii** [comment]
(I was going to do it [here](https://github.com/scikit-build/scikit-build/pull/516), but it would be better to try https://github.com/scikit-build/scikit-build/issues/554.)

**Comment by tdegeus** [comment]
Thanks @henryiii , I will try. The other horse I was betting on was to use FindPythonLibs through pybind11's CMake support and to rely on the FindNumPy you provided in scikit-build. But somehow I'm still doing something wrong I think, because the library is ultimately not installed https://github.com/tdegeus/QPot/pull/36/files

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
@henryiii I think I'm nearly there... I'm able to use scikit-build locally : https://github.com/tdegeus/QPot/pull/36 (I will put some more comments there), however, I get hopeless failures here on conda-build. In particular, I get the error:

```
CMake-installed files must be within the project root.
       Project Root  : /tmp/pip-req-build-3s1kxo05/_skbuild/linux-x86_64-3.6/cmake-install
       Violating File: /home/conda/feedstock_root/build_artifacts/qpot-split_1629792833267/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/./_QPot.cpython-36m-x86_64-linux-gnu.so
```

Do you know what to do about this ?

Note that in the example you linked, I found 
```cmake
if(APPLE)
    set_target_properties(${PYPROJECT_NAME} PROPERTIES INSTALL_RPATH "@loader_path/${CMAKE_INSTALL_LIBDIR}")
else()
    set_target_properties(${PYPROJECT_NAME} PROPERTIES INSTALL_RPATH "$ORIGIN/${CMAKE_INSTALL_LIBDIR}")
endif()
```
I tried both with and without, with exactly the same error message.

Also not that I followed the manual and the example such that 
```cmake
install(TARGETS ${PYPROJECT_NAME} DESTINATION .)
```
but that might not be what is actually needed?

**Comment by tdegeus** [comment]
Found it @henryiii , see https://github.com/scikit-build/scikit-build/issues/588

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
Fixed by https://github.com/conda-forge/qpot-feedstock/pull/33

**Pull request closed without merging**
